### ISSUE TITLE
Geolitecity or country in settings?

### ISSUE THREAD

**Issue by biggen1684** [mindphluxnet/cowrie-logviewer#5]
Hello,

Playing around with your viewer and noticed an issue.  The instructions say to download:

`wget http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz`

But in the cowrie-logviewer.py, the maxmind path points to GeoLite2-Country.mmdb.  I'm assuming City is the correct file?

**Comment by mindphluxnet** [comment]
Country is the correct file, sorry.

2017-03-15 19:52 GMT+01:00 biggen1684 <notifications@github.com>:

**Comment by mindphluxnet** [comment]
Fixed with commit https://github.com/mindphluxnet/cowrie-logviewer/commit/9a660eccbdcf5fe94a5ea1987beb8d9f8a8afb1c
